[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:encrypted_pw_here"
  ]

[http.routers.api]
  rule = "Host(`traefik.your-website.com`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"

